project:
  type: website
  output-dir: docs
  resources:
    - icons
  
  
website:
  title: "Personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - CV.qmd
      - blog.qmd
      - gallery.qmd
      - other-interests.qmd
    tools:
         - icon: github
           href: https://github.com/gretageo/website
         - image: icons/orcid.svg
           href: https://orcid.org/0000-0002-5563-3724
         - texte: ingpan
           href: https://www.ing.pan.pl/pracownicy/strony-naukowcow/greta-brancaleoni
         - image: icons/researchgate.svg
           href: https://www.researchgate.net/profile/Greta-Brancaleoni-2?ev=hdr_xprf
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Greta Brancaleoni"

format:
  html:
    theme: morph
    toc: true

editor: source

