---
title: "Curriculum Vitae"
---

## Personal information
Name\|Greta\
Surname\|Brancaleoni\
e-mail\|greta.brancaleoni\@twarda.pan.pl

## Current position
-   Research assistant at the Institute of Geological Sciences, Polish Academy of Sciences (Warsaw, Poland)

## Education
-   2019 – 2024\|Doctoral program in Earth and Environmental Sciences (EQF 8), Institute of Geological Sciences of the Polish Academy of Sciences in Warsaw (ING PAN, Poland).

-   1/02– 24/05/2019\|Professional Program in Seismic Microzonation and Local Seismic Response, University of Perugia (Italy).

-   2014 – 2016\|Postgraduate program in Geology (EQF 7), University of Bologna (Italy).

-   2011 – 2014\|Undergraduate program in Geological sciences (EQF 6), University of Bologna (Italy)

## Degrees and professional diplomas
-   19/04/2024\|Doctoral degree (PhD) (cum laude). Thesis: Reconstruction of depositional and post-depositional processes at Obishirian sites (Central Asia – Kyrgyzstan). Supervisor: Prof. Maciej T. Krajcarz

-   24/05/2019\|Professional Diploma in Seismic Microzonation and Local Seismic Response. Thesis: Local Seismic Response 2D Case study in Alpine Valley. Supervisors: Dr Giulia Sgattoni (University of Bologna), Prof. Cristina Pauselli (University of Perugia)

-   19/09/2018\|Professional association in Italy

-   25/07/2018\|Qualified to practice as a Geologist in Italy

-   06/10/2016\|Postgraduate degree (MSc) with full marks (110/110). Thesis: New studies in the Etruscan Necropolis of Tarquina (VT) with GPR and resistivity method (https://amslaurea.unibo.it/11854/). Supervisors: Prof. Silvia Castellaro (University of Bologna), Luigi Perricone

-   21/07/2014\|Undergraduate degree (BSc) with first-class honors (110/110 cum laude). Thesis: Geomorphological survey and kinematic features of the Poggio Zampiroli landslide (RA). Supervisor: Prof. Matteo Berti (University of Bologna)

## Relevant training and work experiences
-   June 2024 - now\|Research assistant at INGPAN – Warsaw (Poland) December 2019 – 2021 Technician at the Stable Isotope Laboratory, ISOLAB (LUIS) INGPAN – Warsaw (Poland)
-   June 2017 – 2019\|Geologist and GIS expert at GEO3D s.r.l. Via della Chimica snc 02100, Rieti (RI - Italy); www.geo-3d.it. Relevant activities: Seismic Microzonation studies for Rieti, Cantalice and Accumuli municipalities hit by the 2016-2017 seismic events under the supervision of University of Roma 1 – La Sapienza and MS Center
-   November 2016 – June 2017\|GIS Analyst at Guglielmo Marconi Labs Via Fattori 6, Casalecchio di Reno (BO - Italy), www.new.labs.it
-   April 2016 – June 2016\|Internship at the British Geological Survey (BGS) - Environmental Science Centre, Keyworth – Nottingham (UK). Activities: BGS landslide impact library, characterizing landslides in the White Peak and Derbyshire, investigation of a landslip in Cressbrook Dale, Derbyshire, geotechnical characterization of soil samples in the BGS Geotechnical Laboratory

## Relevant courses
-   30 – 31 March 2023\|Micromorphology workshop “Working Group on Archaeological Soil Micromorphology (WASM)” at University of Reading
-   6 – 10 March 2023\|International course on Palaeopedology. IUSS, INQUA
-   26 – 30 July 2021\|Archaeological Soil and Sediment Micromorphology Course. Lecturers: Takis Karkanas and Paul Goldberg at “The Malcolm H. Wiener Laboratory For Archaeological Science” - THE AMERICAN SCHOOL OF CLASSICAL STUDIES AT ATHENS (Greece)

## Research projects
-   Dec 2024 – 2025\|Research activity under MINIATURA financed by National Science Centre, Poland "Micro-stratigraphic and multi-method approach to tackling biogenic deposits: The case study of Biśnik Cave (Poland)", 2024/08/X/ST10/01585. Principal Investigator (ING PAN).
-   2023 – 2027\|Research project financed by programme ANR, France “Archaeology and paleoecology of high-altitude ecosystems in Central Asia’s landlocked mountains from the Late Glacial to the middle Holocene” (PaleoCALM), PI: W. Rendu (IFEAC). A co-investigator. -Jan 2022 – Oct 2024\|Research project financed by National Science Centre, Poland "Palaeoecological approach to position stands: Palaeoenvironmental context of settlement provided in southern Poland from the late Middle to Upper Palaeolithic", 2020/39/B/HS3/0932. PI: C. Berto, University of Warsaw. A co-investigator and scholarship holder.
-   Jan - June 2023\|Research project “Multidisciplinary microregional studies of the Middle Palaeolithic in the south-western Chatkal Range (western Tian Shan piedmonts, Uzbekistan)”, 2017/25/B/HS3/00520. PI: Prof. Karol Szymczak, University of Warsaw. A co-investigator on a contract.
-   Apr 2019 – 2022\|Research project financed by National Science Centre, Poland "Stratigraphy, depositional and post-depositional processes at the Palaeolithic cave sites in Central Asia", 2018/29/B/ST10/00906. PI: M. Krajcarz, Institute of Geological Sciences, Polish Academy of Sciences. A co-investigator and scholarship holder.

## Research visits
-   Jan-April 2025 Research visitor within the GACT research visiting program (https://geogenarch-tuebingen.de/), Senckenberg Centre for Human Evolution and Palaeoenvironment, Tübingen

## Research fieldworks
### Central Asia
#### Uzbekistan
-   Kuksaray-2 archaeological site (Angren), geoarchaeological investigation at archaeological excavations led by University of Warsaw in cooperation with Institute of Archaeology of Uzbekistan Academy of Sciences, 15.08-1.09.2024
-   Kuksaray-2 archaeological site (Angren), geoarchaeological investigation at archaeological excavations led by University of Warsaw in cooperation with Institute of Archaeology of Uzbekistan Academy of Sciences, 12-26.07.2022

#### Tajikistan
-   Geoarchaeological surveys and investigation at several archaeological sites, such as Istykskaya Cave and Kurteke rockshelter in collaboration with Institute of History, Archaeology and Ethnography of the National Academy of Sciences of the Republic of Tajikistan, 04.06.2023-03.07.2023

#### Kyrgyzstan
-   Surungur rock-shelter, Sel'Ungur Cave, Obishir 5, Kyzyl-Koshun sites(Aydarken), geoarchaeological investigation at archaeological excavations, 30.07-17.08.2022.
-   Sel'Ungur Cave and Obishir 1 and Obishir 5 sites (Aydarken), geoarchaeological investigation at archaeological excavations led by Institute of Archaeology and Ethnography, Siberian Branch of the Russian Academy of Sciences (in cooperation with Bishkek University), 22.08–07.09.2019.

### Central Europe
#### Poland
-   Raj Cave (Chęciny – Poland), geoarchaeological investigations during archaeological excavation led by University of Warsaw, February, June and July 2024.
-   Wisieluch Cave (Kostkowice – Poland), geoarchaeological investigations during archaeological excavation led by University of Warsaw, 7.09–20.09.2022.
-   Poręba Dzierżna site 24, prehistoric flint mine (Udórz – Poland), Nicolaus Copernicus University, geoarchaeological investigation during the archaeological excavation.
-   Perspektywiczna Cave (Udórz – Poland), geoarchaeological investigation during archaeological excavation led by Nicolaus Copernicus University in Toruń (Poland), 22.06-12.07.2019

## Non-scientific publications
Emidio di Treviri research group (2018). Sul Fronte del Sisma – Una inchiesta militante sul post-terremoto dell’Appennino Centrale (2016-2017) – Deriveapprodi – ISBN978-88-6548-238-4. pp 320

## Awards
-   ING PAN scholarship for best young scientist, academic year 2024/2025
-   ING PAN Director scholarship for best PhD student, academic years 2021/2022, 2022/2023
-   ING PAN scholarship for PhD students, 2020/2021
-   ING PAN scholarship for PhD students, 2019/2020

## Memberships
-   2025 Junior member of the Associazione Italiana per lo Studio del Quaternario - Italian Association for the Study of the Quaternary - AIQUA


*Latest update 26/04/2025*
