---
title: "Publications"
---

-   **Brancaleoni, G.**, Shnaider, S., Lempart-Drozd, M., Goleń, J., Deput, E., kyzy, S.A., Abdykanova, A., Krajcarz, M.T., 2024. A site formation history of Obishir-5, the earliest Neolithic site in the Fergana Valley (Kyrgyzstan). Archaeological and Anthropological Sciences 16. <https://doi.org/10.1007/s12520-024-01967-w>

-   Kot, M., Kogai, S., Pavlenok, G., Gryczewska, N., **Brancaleoni, G.**, Krajcarz, M.T., Moska, P., Leloch, M., Khudjanazarov, M., Szymczak, K., Muhtarov, G., Pavlenok, K., 2024. New data for asymmetric core reduction in western Tian Shan piedmonts: Ertash Sai 2 open-air site. Lithic Technology, 1–22. <https://doi.org/10.1080/01977261.2024.2319429>

-   Gryczewska, N., Kot, M., Berto, C., **Brancaleoni, G.**, Krajcarz, M.T., Cyrek, K., Sudoł-Procyk, M., Wojenka, M., Wilczyński, J.W., Chmielewska, M., Sulwiński, M.S., Suska-Malawska, M., 2023. Tracing ephemeral human occupation through archaeological, palaeoenvironmental and molecular proxies at Łabajowa Cave. Antiquity, 97(396). <https://doi.org/10.15184/aqy.2023.147>

-   **Brancaleoni, G.**, Kot, M., Shnaider, S., Mroczek, P., Kurbanov, R., Abdykanova, A., Alisher kyzy, S., Khudjanazarov, M., Pavlenok, K., Krajcarz, M.T., 2023. A closer look at clasts and groundmass: Micromorphological features in sediments with archaeological significance in Obishir and Katta Sai complexes (Central Asia). Journal of Archaeological Science: Reports 51, 104118. <https://doi.org/10.1016/j.jasrep.2023.104118>

-   Ceregatti, L., Berto, C., Fewlass, H., Baca, M., Luzi, E., **Brancaleoni, G.**, Pereswiet-Soltan, A., Peresani, M., 2023. Integration of direct radiocarbon dating, genetic studies and taxonomy of small mammals to investigate the chronology of past climatic oscillations: The Last Glacial Maximum sequence of Grotta della Ferrovia (Fabriano, Italy). Quaternary Science Reviews 309, 108095. <https://doi.org/10.1016/j.quascirev.2023.108095>

-   **Brancaleoni, G**., Kot, M., Shnaider, S., Abdykanova, A., Alisher kyzy, S., Khudjanazarov, M., Pavlenok, K., Krajcarz, M.T., 2022. Pebble in the Wind. Micromorphological Features at the Contact between Gravelly Clasts and Silty Groundmass in Loess-Debris Sediments, Central Asiatic Loess Zone. SSRN Electronic Journal. <https://doi.org/10.2139/SSRN.4142341>

-   **Brancaleoni, G.**, Shnaider, S., Osipova, E., Danukalova, G., Kurbanov, R., Deput, E., Alisher kyzy, S., Abdykanova, A., Krajcarz, M.T., 2022. Depositional history of a talus cone in an arid intermontane basin in Central Asia: An interdisciplinary study at the Late Pleistocene–Late Holocene Obishir-I site, Kyrgyzstan. Geoarchaeology 37, 350–373. <https://doi.org/10.1002/gea.21892>

-   Taylor, W.T.T., Pruvost, M., Posth, C., Rendu, W., Krajcarz, M.T., Abdykanova, A., **Brancaleoni, G.**, Spengler, R., Hermes, T., Schiavinato, S., Hodgins, G., Stahl, R., Min, J., Alisher kyzy, S., Fedorowicz, S., Orlando, L., Douka, K., Krivoshapkin, A., Jeong, C., Warinner, C., Shnaider, S., 2021. Evidence for early dispersal of domestic sheep into Central Asia. Nature Human Behaviour. <https://doi.org/10.1038/s41562-021-01083-y>

-   Osipova, E., Danukalova, G., **Brancaleoni, G.**, Krajcarz, M.T., Abdykanova, A., Shnaider, S., 2020. Palaeoenvironmental conditions of the Palaeolithic–Neolithic transition in the Fergana Valley (Central Asia) – New data inferred from fossil mollusсs in Obishir-V rockshelter (Kyrgyzstan). Quaternary International. <https://doi.org/10.1016/j.quaint.2020.11.009>

-   Shnaider, S.V., Alisher kyzy, S., Selin, D.V., Rendu, W., Abdykanova, A., **Brancaleoni, G.**, Krajcarz, M.T. Krivoshapkin, A.I., 2019. Results of Field Studies at the Obishir-5 Site in 2018–2019. Problems of Archaeology, Ethnography, Anthropology of Siberia and Neighboring Territories XXV, 286–292.

-   **Brancaleoni, G.**, Banks, V.J., Leoncini, C., Kirkham, M., Thorpe, J., Castellaro, S., 2016. Peter’s Stone, Cressbrook Dale, Derbyshire: Landslide or paraglacial feature? Mercian Geologist 19.

*Latest update 26/04/2025*
